name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
#          - windows-latest
        ocaml-compiler:
          - 5
          - 4.14
        coq_version:
          - "8.20.1"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Set-up Rocq for testing
        run: |
          opam install coq.${{ matrix.coq_version }}

      - run: |
          opam install -y --deps-only . && opam exec -- make all test
