on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14
          opam-repositories: |
            coq-released: https://coq.inria.fr/opam/released
            default: https://github.com/ocaml/opam-repository.git

      - name: Build rocqnavi
        run: opam install -y --deps-only . && opam exec -- make

      - name: Setup Coq temporary fix for the Dependency Graph
        run: opam install -y coq.8.20.1

      - name: top site
        run: mkdir html && cp -r .github/workflows/resources/* html/

      ## Mathcomp Analysis ----------
      - name: Clone Mathcomp Analysis
        uses: actions/checkout@v4
        with:
          repository: math-comp/analysis
          path: analysis
          ref: 1.10.0

      - name: Build Mathcomp Analysis
        run: cd analysis/ && opam install -y --deps-only . && opam exec -- make all install
      - run: |
          opam exec -- tools/generate-mathcomp-analysis.sh "1.9.0(rocqnavi-${GITHUB_SHA::8})"
          tree html/
      ## ----------------------------

      ## Infotheo -------------------
      - name: Clone Infotheo
        uses: actions/checkout@v4
        with:
          repository: affeldt-aist/infotheo
          path: infotheo
          ref: 0.9.1

      - name: Build Infotheo
        run: cd infotheo/ && opam install -y --deps-only . && opam exec -- make all install
      - run: |
             opam exec -- tools/generate-infotheo.sh "0.9.1(rocqnavi-${GITHUB_SHA::8})"
             tree html/
      ## ----------------------------

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'html/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
