name: Docker CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        analysis_tag:
          - '1.12.0'
        image:
          - 'yoshihiro503/mathcomp-analysis:1.12.0-coq-8.20-ocaml-4.14-flambda'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'rocq-navi.opam'
          custom_image: ${{ matrix.image }}
          before_script: |
            startGroup "Build Rocqnavi"
              sudo apt-get install -y graphviz
              sudo chown -R 1000:1000 .
              make
            endGroup
          script: |
            startGroup "Do Rocqnavi"
              export MATHCOMP_ANALYSIS=$OPAM_SWITCH_PREFIX/lib/coq/user-contrib/mathcomp/
              export REVISION=${{ matrix.analysis_tag }}
              export DIR=$(pwd `dirname .`)
              export OUTDIR=$DIR/html/analysis-${{ matrix.analysis_tag }}
              export CoqProject=$OPAM_SWITCH_PREFIX/.opam-switch/sources/coq-mathcomp-analysis/_CoqProject
              ./tools/generate-mathcomp-analysis.sh
            endGroup

      - name: Upload htmldoc as artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            html

