name: Analysis [Build HTML and upload as Artifact]

on:
  push:
  pull_request:
  schedule:
    - cron: 0 18 * * * # every night (03:00 JST)

jobs:
  generate-artifact:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        analysis_tag:
          - '1.12.0'
        image:
          - 'yoshihiro503/mathcomp-analysis:1.12.0-coq-8.20-ocaml-4.14-flambda'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: set the variables for push event
        if: ${{ github.event_name == 'push' }}
        run: |
          branch_name=${{ github.ref_name }}
          short_sha=$(git rev-parse --short ${{ github.sha }})
          echo "destination_dir=sample_"$branch_name_$short_sha >> $GITHUB_ENV

      - name: set the variables for PR event
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          branch_name=${{ github.head_ref }}
          echo "destination_dir=sample_$branch_name" >> $GITHUB_ENV

      - name: set the variables for scheduled event
        if: ${{ github.event_name == 'schedule' }}
        run: |
          name=${{ github.action }}
          echo "destination_dir=nightly_$name" >> $GITHUB_ENV

      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'rocq-navi.opam'
          custom_image: ${{ matrix.image }}
          before_script: |
            startGroup "Build Rocqnavi"
              sudo apt-get install -y graphviz
              sudo chown -R 1000:1000 .
              opam install -y coq-lsp
              make
            endGroup
          script: |
            startGroup "Do Rocqnavi"
              export MATHCOMP_ANALYSIS=$OPAM_SWITCH_PREFIX/lib/coq/user-contrib/mathcomp/
              export REVISION=${{ matrix.analysis_tag }}-rocqnavi-${{ env.destination_dir }}
              export DIR=$(pwd `dirname .`)
              export OUTDIR=$DIR/html/analysis-${{ matrix.analysis_tag }}
              export ANALYSIS_SRC=$OPAM_SWITCH_PREFIX/.opam-switch/sources/coq-mathcomp-analysis
              ./tools/generate-mathcomp-analysis.sh
            endGroup

      - name: Upload htmldoc as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.destination_dir }}
          path: |
            html
